---
version: "2.1"
services:
  syslog-ng:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: syslog-ng
    environment:
      - TZ=Asia/Bangkok
    volumes:
      #- /config:/config
      - /var/log/project/syslog:/var/log 
    ports:
      - 514:514/udp
      - 514:514/tcp
    restart: unless-stopped