version: '3'

services:

  prometheus:
    image: "prom/prometheus:latest"
    hostname: "prometheus"
    restart: always
    networks:
    - monitoring-net
    ports:
    - "9090:9090"
    user: nobody
    volumes:
    # - "./config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro"
    # - "./config/prometheus/targets.yml:/etc/prometheus/targets.yml:ro"
    # - "./config/prometheus/rules:/etc/prometheus/rules"
    - "prometheus_data:/prometheus"
    command:
    - "--config.file=/etc/prometheus/prometheus.yml"
    - "--storage.tsdb.path=/prometheus"
    - "--storage.tsdb.retention.time=30d"
    - '--web.console.libraries=/usr/share/prometheus/console_libraries'
    - '--web.console.templates=/usr/share/prometheus/consoles'
    - '--web.enable-admin-api'

  # blackbox-exporter:
  #   image: "prom/blackbox-exporter:latest"
  #   hostname: "blackbox"
  #   restart: always
  #   networks:
  #   - monitoring-net
  #   ports:
  #   - "9115:9115"
  #   volumes:
  #   - "./config/blackbox-exporter/blackbox-exporter.yml:/etc/prometheus/blackbox-exporter.yml"
  #   command:
  #   - "--config.file=/etc/prometheus/blackbox-exporter.yml"

  grafana:
    image: "grafana/grafana:9.1.5"
    hostname: "grafana"
    restart: always
    # env_file: configuration.env
    networks:
    - monitoring-net
    ports:
    - "3000:3000"
    volumes:
    - "grafana_data:/var/lib/grafana"
    # - "./config/grafana/provisioning:/etc/grafana/provisioning"

  # telegraf:
  #   image: telegraf:1.23-alpine
  #   hostname: "telegraf"
  #   restart: always
  #   env_file: configuration.env
  #   networks:
  #   - monitoring
  #   ports:
  #   - "8125:8125/udp"
  #   - "1234:1234"
  #   volumes:
  #   - ./config/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf
  #   depends_on:
  #     - influxdb
  #   links:
  #     - influxdb

  influxdb:
    image: influxdb:2.2
    hostname: "influxdb"
    restart: always
    #env_file: configuration.env
    networks:
    - monitoring-net
    ports:
      - "8082:8082"
      - "8086:8086"
      - "8089:8089"
    volumes:
      - ./:/imports
      - influxdb_data:/var/lib/influxdb


volumes:
  prometheus_data:
  influxdb_data:
  grafana_data:

networks:
  monitoring-net: 