version: "3.8"

services:
  ghost:
    image: ghost:latest
    restart: always
    ports:
      - "3020:2368"
    depends_on:
      - database
    environment:
      url: https://blog.ce.kmitl.cloud
      database__client: mysql
      database__connection__host: database
      database__connection__user: ghost
      database__connection__password: ghostpass
      database__connection__database: ghostdb
    volumes:
      - content-volumes:/var/lib/ghost/content

  database:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysqlpass
      MYSQL_USER: ghost
      MYSQL_PASSWORD: ghostpass
      MYSQL_DATABASE: ghostdb
    volumes:
      - data-volumes:/var/lib/mysql


volumes:
  data-volumes:
  content-volumes: