version: '3.8'
services:
  proxy:
    image: 'jc21/nginx-proxy-manager:latest'
    hostname: "ng-proxy"
    container_name: ng-proxy
    environment:
      - TZ=Asia/Bangkok
    restart: always
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - proxy-data:/data
      - proxy-cert:/etc/letsencrypt

volumes:
  proxy-data:
  proxy-cert: